# Generated by Django 4.2.3 on 2023-07-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='URL'),
        ),
    ]
